openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3000/
#POST api/account/login - логин
#POST api/account/logout - логоут
#POST api/account - регистрация
#GET api/account - получение информации о текущем мользоватлеле
#PUT api/account - редактирование данных текущего пользователя
#OST api/account/restore - востановление пароля (запрос на востановление)
#PUT api/account/restore - изменение пароля
#GET api/article - получение статей
#GET api/artiles/:id получение конкретной статьи
paths:
  /account/login:
    post:
      tags:
        - Account 
      requestBody:
        content:
          application/json: 
            schema: 
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json: 
              schema: 
                $ref: "#/components/schemas/LoginResponse"
        '404':
          $ref: '#/components/responses/NotFound'
  /account/logout:
    post:
      tags:
        - Account 
      responses:
        '200':
          description: OK
  /account:
    get:
      tags:
        - Account 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/User'
    put:
      tags:
        - Account 
      requestBody:
        content:
          application/json: 
            schema: 
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
    post:
      tags:
        - Account 
      responses:
        '200':
          description: OK
  /api/account/restore:
    post:
      tags:
        - Account 
      requestBody:
        content:
          application/json: 
            schema: 
              $ref: '#/components/schemas/RestoreRequest'
      responses:
        '200':
          description: OK
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/RestoreRespose'

    put:
      tags:
        - Account 
      requestBody:
        content:
          application/json: 
            schema: 
              $ref: '#/components/schemas/RestoreCodeRequest'
      responses:
        '200':
          description: OK
        '400':
            description: Not found
  /article: 
    get:
      tags:
        - Article 
      responses:
        '200':
          description: OK
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/ArrayOfArticle'
  /article/{id}:
    get:
      tags:
        - Article
      parameters:
        - in: path
          description: article id
          name: id
          required: true
          schema: 
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/Article'
components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    # Schema for error response body
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    User:
      type: object
      properties:
        id:
          type: integer
          description: The user ID.
        name:
          type: string
          description: The user name.
        last_name:
          type: string
          description: The user name.
    ArrayOfArticle:
      type: array
      items:
        $ref : '#/components/schemas/Article'
    Article:
      type: object
      properties:
        id:
          type: integer
          description: The artile ID.
        title:
          type: string
          description: Article title.
        text: 
          type: string
          description: article text
        readed: 
          type: boolean
          description: article is readed or not
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password: 
          type: string
    LoginResponse:
      type: object
      properties: 
        token: 
          type: string
    RegisterRequest:
      properties:
        email: 
          type: string
        name:
          type: string
        last_name:
          type: string
        password: 
          type: string
        
    RestoreRequest:
      type: object
      properties: 
        email: 
          type: string
    RestoreRespose:
      type: object
      properties:
        restore_token:
          type: string

    RestoreCodeRequest:
      type: object
      properties: 
        restore_token: 
          type: string
        password: 
          type: string
          description: New password
        
    IntValue:
      type: integer

